### ISSUE TITLE
Exposing port 8000 not required

### ISSUE THREAD

**Issue by 0xbadshah** [appsecco/docker-datasploit#2]
The previous [commit](https://github.com/DataSploit/datasploit/commit/8128b07a55874f691608e319968a0bf912a31d22) by @upgoingstar shows that GUI is completely removed. So now it is of no use expose port 8000 to host.

Changes required in [#L48](https://github.com/appsecco/docker-datasploit/blob/master/Dockerfile#L48) of `Dockerfile` and also the documentation in `README.md` file.

**Comment by madhuakula** [comment]
@Chan9390 I will confirm and update.

Thanks

**Comment by madhuakula** [comment]
Thanks @Chan9390, confirmed that datasploit is not supporting web UI. I will update the docker image soon.
https://www.slideshare.net/upgoingstar1/datasploit-tool-demo-at-null-bangalore-march-meet#15

**Comment by madhuakula** [comment]
Thanks @Chan9390 for heads up. Closing this issue, new docker image has been updated with v1.0
