### ISSUE TITLE
Datasploit crashing for unknown reason?

### ISSUE THREAD

**Issue by 7MinSec** [appsecco/docker-datasploit#3]
Hi there,

I followed the directions to get the docker up and going, API keys put in config file, etc. so I *think* all is well.  I did my first domain recon and got to this section:

```
---> Finding Pagelinks:
```

And then after finding 2 dozen links or so and listing them out, the tool crashes with:

```
Traceback (most recent call last):
  File "domainOsint.py", line 435, in <module>
    main()
  File "domainOsint.py", line 431, in main
    do_everything(domain)
  File "domainOsint.py", line 265, in do_everything
    subdomains_from_netcraft(domain)
  File "/opt/datasploit/domain_subdomains.py", line 150, in subdomains_from_netcraft
    if num_subdomains[0] != str(0):
IndexError: list index out of range
```
I'm a little new to the docker world, but for the heck of it I tried a `git pull master` to get the latest repository but that seemed to make things worse as now the datasploit won't run at all:

```
Traceback (most recent call last):
  File "domainOsint.py", line 13, in <module>
    run(domain)
  File "domainOsint.py", line 8, in run
    osint_runner.run("domain", "domain", domain)
  File "/opt/datasploit/osint_runner.py", line 15, in run
    if not x.ENABLED:
AttributeError: 'module' object has no attribute 'ENABLED'
```
Please let me know if you have any ideas?

Thanks,
Brian

**Comment by madhuakula** [comment]
Hi @braimee 

It seems datasploit has been updated, I will update the docker image.

Thanks

**Comment by madhuakula** [comment]
Hi @braimee 

Update the new docker image with v1.0. 

Also looks like your issue is with code. This repository is for Docker image only, The questions regarding code we can move to https://github.com/DataSploit/datasploit

Thanks

**Comment by 7MinSec** [comment]
Thanks, I'll try the updated Docker on my next assessment and report back if there are issues!

**Comment by meetgyn** [comment]
Estou com mesmo problema, ja atualizei todudo e não consigo utilizar.. Estava funcionando perfeitamente, dai parou do nada
